name: .NET Core Desktop App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: YourSolutionName.sln                       # Replace with your solution file name (e.g., MyApp.sln)
      Test_Project_Path: YourTestProject/MyApp.Tests.csproj     # Replace with the path to your test project
      Wap_Project_Directory: YourApp.Package                    # Replace with your WAP project directory
      Wap_Project_Path: YourApp.Package/YourApp.Package.wapproj # Replace with the path to your WAP project

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore and Build Solution
      run: |
        dotnet restore $env:Solution_Name
        dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

    - name: Run Unit Tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }}

    - name: Decode Signing Certificate (PFX)
      if: secrets.Base64_Encoded_Pfx != ''
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Package the Application
      run: msbuild $env:Wap_Project_Path /p:Configuration=${{ matrix.configuration }} /p:AppxBundle=Always /p:PackageCertificateKeyFile=$certificatePath /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}

    - name: Remove the Signing Certificate
      if: secrets.Base64_Encoded_Pfx != ''
      run: Remove-Item -path $certificatePath

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: AppPackages
        path: ${{ env.Wap_Project_Directory }}/AppPackages
